export const PROJECT_TEMPLATES = {
  Residential: {
    basements: {
      enabled: true,
      count: 2,
      floors: [
        {
          id: "B2",
          level: "B2",
          name: "Basement 2",
          usage: "Parking",
          description: "Car parking level 2",
          capacity: 60,
          fireDetection: true,
          ventilation: "Mechanical",
          accessibility: true,
          additionalNotes: "",
        },
        {
          id: "B1",
          level: "B1",
          name: "Basement 1",
          usage: "Parking",
          description: "Car parking level 1",
          capacity: 80,
          fireDetection: true,
          ventilation: "Mechanical",
          accessibility: true,
          additionalNotes: "",
        },
      ],
    },
    ground: {
      enabled: true,
      usage: "Lobby",
      description: "Main entrance lobby with reception",
    },
    podiums: {
      enabled: true,
      count: 1,
      floors: [
        {
          id: "P1",
          level: "P1",
          name: "Podium Level 1",
          usage: "Amenities",
          description: "Swimming pool, gym, clubhouse",
          capacity: 100,
          features: ["Swimming Pool", "Gym", "Clubhouse"],
          openArea: true,
          landscaping: true,
          accessibility: true,
          additionalNotes: "",
        },
      ],
    },
    wings: {
      count: 2,
      wings: [
        {
          name: "Wing A",
          floors: {
            commercial: { count: 0, startFloor: 1, floorType: "Office" },
            residential: { count: 12, startFloor: 1, floorType: "Apartments" },
          },
        },
        {
          name: "Wing B",
          floors: {
            commercial: { count: 0, startFloor: 1, floorType: "Office" },
            residential: { count: 12, startFloor: 1, floorType: "Apartments" },
          },
        },
      ],
    },
    amenities: {
      clubhouse: true,
      swimmingPool: true,
      garden: true,
      gym: true,
      playArea: true,
      parking: { capacity: 250 },
    },
  },
  Commercial: {
    basements: {
      enabled: true,
      count: 3,
      floors: [
        {
          id: "B3",
          level: "B3",
          name: "Basement 3",
          usage: "Storage",
          description: "Storage and utilities",
          capacity: 500,
          fireDetection: true,
          ventilation: "Mechanical",
          accessibility: false,
          additionalNotes: "Utility access only",
        },
        {
          id: "B2",
          level: "B2",
          name: "Basement 2",
          usage: "Parking",
          description: "Staff parking",
          capacity: 80,
          fireDetection: true,
          ventilation: "Mechanical",
          accessibility: true,
          additionalNotes: "",
        },
        {
          id: "B1",
          level: "B1",
          name: "Basement 1",
          usage: "Parking",
          description: "Visitor parking",
          capacity: 120,
          fireDetection: true,
          ventilation: "Mechanical",
          accessibility: true,
          additionalNotes: "",
        },
      ],
    },
    ground: {
      enabled: true,
      usage: "Retail",
      description: "Ground floor retail and commercial spaces",
    },
    podiums: {
      enabled: true,
      count: 2,
      floors: [
        {
          id: "P1",
          level: "P1",
          name: "Podium Level 1",
          usage: "Parking",
          description: "Commercial parking level 1",
          capacity: 150,
          features: [],
          openArea: false,
          landscaping: false,
          accessibility: true,
          additionalNotes: "",
        },
        {
          id: "P2",
          level: "P2",
          name: "Podium Level 2",
          usage: "Mixed",
          description: "Parking + food court",
          capacity: 100,
          features: ["Café", "Business Center"],
          openArea: true,
          landscaping: false,
          accessibility: true,
          additionalNotes: "",
        },
      ],
    },
    wings: {
      count: 1,
      wings: [
        {
          name: "Tower A",
          floors: {
            commercial: { count: 20, startFloor: 1, floorType: "Office" },
            residential: { count: 0, startFloor: 21, floorType: "Apartments" },
          },
        },
      ],
    },
    amenities: {
      clubhouse: false,
      swimmingPool: false,
      garden: true,
      gym: false,
      playArea: false,
      parking: { capacity: 400 },
    },
  },
  "Mixed-use": {
    basements: {
      enabled: true,
      count: 2,
      floors: [
        {
          id: "B2",
          level: "B2",
          name: "Basement 2",
          usage: "Storage",
          description: "Central storage and utilities",
          capacity: 300,
          fireDetection: true,
          ventilation: "Mechanical",
          accessibility: false,
          additionalNotes: "",
        },
        {
          id: "B1",
          level: "B1",
          name: "Basement 1",
          usage: "Parking",
          description: "Mixed-use parking",
          capacity: 100,
          fireDetection: true,
          ventilation: "Mechanical",
          accessibility: true,
          additionalNotes: "",
        },
      ],
    },
    ground: {
      enabled: true,
      usage: "Retail",
      description: "Mixed retail and commercial entrance",
    },
    podiums: {
      enabled: true,
      count: 1,
      floors: [
        {
          id: "P1",
          level: "P1",
          name: "Podium Level 1",
          usage: "Mixed",
          description: "Amenities + commercial parking",
          capacity: 150,
          features: ["Gym", "Swimming Pool", "Café"],
          openArea: true,
          landscaping: true,
          accessibility: true,
          additionalNotes: "",
        },
      ],
    },
    wings: {
      count: 2,
      wings: [
        {
          name: "Commercial Tower",
          floors: {
            commercial: { count: 8, startFloor: 1, floorType: "Office" },
            residential: { count: 0, startFloor: 9, floorType: "Apartments" },
          },
        },
        {
          name: "Residential Tower",
          floors: {
            commercial: { count: 0, startFloor: 1, floorType: "Office" },
            residential: { count: 15, startFloor: 1, floorType: "Apartments" },
          },
        },
      ],
    },
    amenities: {
      clubhouse: true,
      swimmingPool: true,
      garden: true,
      gym: true,
      playArea: true,
      parking: { capacity: 300 },
    },
  },
};

export const USAGE_TYPES = {
  basement: [
    "Parking",
    "Storage",
    "Utilities",
    "Retail",
    "Restaurant",
    "Gym",
    "Swimming Pool",
    "Mechanical Room",
    "Generator Room",
    "Water Treatment",
    "Custom",
  ],
  ground: [
    "Lobby",
    "Retail",
    "Restaurant",
    "Banking",
    "Office",
    "Mixed",
    "Custom",
  ],
  podium: [
    "Amenities",
    "Parking",
    "Retail",
    "Office",
    "Recreation",
    "Swimming Pool",
    "Gym",
    "Banquet Hall",
    "Terrace Garden",
    "Mixed",
    "Custom",
  ],
};

export const UNIT_TEMPLATES = {
  "1BHK": {
    bedrooms: 1,
    washrooms: { attached: 1, common: 0 },
    balconies: ["living"],
    notes: "Compact 1 bedroom unit",
  },
  "2BHK": {
    bedrooms: 2,
    washrooms: { attached: 1, common: 1 },
    balconies: ["living", "bedroom"],
    notes: "Standard 2 bedroom unit",
  },
  "3BHK": {
    bedrooms: 3,
    washrooms: { attached: 2, common: 1 },
    balconies: ["living", "bedroom", "bedroom"],
    notes: "Spacious 3 bedroom unit",
  },
  "4BHK": {
    bedrooms: 4,
    washrooms: { attached: 3, common: 1 },
    balconies: ["living", "bedroom", "bedroom"],
    notes: "Large 4 bedroom unit",
  },
  Duplex: {
    bedrooms: 3,
    washrooms: { attached: 2, common: 1 },
    balconies: ["living", "bedroom", "terrace"],
    notes: "Duplex unit with terrace",
  },
};

export const PHASE_TEMPLATES = {
  residential: [
    {
      id: 1,
      name: "Phase 1",
      startDate: "2025-09-01",
      endDate: "2027-06-30",
      description: "Residential towers with podium parking",
      estimatedUnits: "120",
    },
    {
      id: 2,
      name: "Phase 2",
      startDate: "2027-01-01",
      endDate: "2028-03-31",
      description: "Additional residential block",
      estimatedUnits: "80",
    },
  ],
  commercial: [
    {
      id: 1,
      name: "Phase 1",
      startDate: "2025-09-01",
      endDate: "2027-12-31",
      description: "Main commercial tower",
      estimatedUnits: "150",
    },
  ],
  mixed: [
    {
      id: 1,
      name: "Commercial Phase",
      startDate: "2025-09-01",
      endDate: "2027-03-31",
      description: "Commercial tower and retail",
      estimatedUnits: "100",
    },
    {
      id: 2,
      name: "Residential Phase",
      startDate: "2026-06-01",
      endDate: "2028-06-30",
      description: "Residential towers",
      estimatedUnits: "200",
    },
  ],
};
